// import './globals.css'

import Image from 'next/image'
import { Roboto } from 'next/font/google'

import { Header } from '@/styles/app'
import logoImg from '../assets/logo.svg'
import StitchesRegistry from './registry'

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StitchesRegistry>
          <Header>
            <Image src={logoImg} alt="" />
          </Header>

          {children}
        </StitchesRegistry>
      </body>
    </html>
  )
}
